name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: fiis-api
          environment-file: ambiente.yml
          python-version: 3.10
          auto-activate-base: false

      - name: Debug Conda Env
        run: |
          conda info
          conda env list
          conda config --show
          cat ambiente.yml
          conda env update -n fiis-api -f ambiente.yml

      - name: Verificar Conda e Python
        run: |
          conda info
          python --version
