name: Build com Conda

on:
  push:
    branches: [principal]
  pull_request:
    branches: [principal]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11
        environment-file: environment.yml
        activate-environment: fiis-api

    - name: Verificar instalação
      run: |
        python --version
        pip list

    - name: Rodar a aplicação (opcional)
      run: |
        python app.py  # ou o nome correto do seu arquivo
