name: CI - Rodar API Flask com timeout

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flask-api-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Miniconda e ambiente Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          environment-file: environment.yml
          activate-environment: api_fiis_env
          miniconda-version: "latest"

      - name: Verificar Python e pacotes
        shell: bash -l {0}
        run: |
          python --version
          conda list

      - name: Rodar Flask com timeout de 15s
        shell: bash -l {0}
        run: |
          echo "Iniciando Flask com timeout..."
          timeout 15s python APIFIISPUCPR.py || [[ $? == 124 ]]

      - name: Finalização
        run: echo "✅ Workflow finalizado com sucesso!"
