- name: Configurar canais Conda
  run: |
    conda config --remove-key channels || true
    conda config --add channels defaults
    conda config --add channels conda-forge
    conda config --set channel_priority strict
