name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean conda cache
        run: conda clean --all --yes

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10
          environment-file: environment.yml
          activate-environment: api_fiis_env
          use-only-tar-bz2: true

      - name: Show conda info and environment
        run: |
          conda info
          conda list

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run tests
        shell: bash -l {0}
        run: |
          which python
          python --version
          conda list
          pytest
