name: Teste Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          use-mamba: false
          miniconda-version: "latest"
          auto-activate-base: false   # <- IMPORTANTE! Não ativa 'base'

      - name: Criar ambiente Conda com environment.yml
        run: conda env create -f environment.yml

      - name: Ativar ambiente e verificar Python
        run: conda activate api_fiis_env && python --version
        shell: bash -l {0}

      - name: Executar script principal
        run: conda activate api_fiis_env && python APIFIISPUCPR.py
        shell: bash -l {0}
