name: python-package-conda.yml

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: api_fiis_env
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run tests
        shell: bash -l {0}  # importante para ativar o conda
        run: |
          which python
          python --version
          pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step (placeholder)
        run: echo "Deploying..."
